default_platform(:ios)

platform :ios do
  desc "Build and test the iOS project"
  lane :build_and_test do
  ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"
    scan(
      project: "Project.xcodeproj",
      scheme: "Project",
      clean: true
    )
  end
end
