name: iOS Fastlane CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Install Fastlane
        run: gem install fastlane -NV

      - name: Install project dependencies
        run: bundle install

      - name: Run Fastlane build_and_test
        run: bundle exec fastlane build_and_test
