name: iOS Fastlane CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Use secret as environment variables 
        run: echo "API key is set"
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Set up latest Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'

      - name: List available simulators
        run: xcrun simctl list devices

      - name: Install Fastlane
        run: gem install fastlane -NV

      - name: Install project dependencies
        run: bundle install

      - name: Run Fastlane build_and_test
        run: bundle exec fastlane build_and_test
